spring:
  application:
    name: monitor-test


thead:
  pool:
    executor:
      config:
        core-pool-size: 5
        max-pool-size: 200
        keep-alive-time: 10
        block-queue-size: 1000
        policy: AbortPolicy


monitor:
  thead:
    pool:
      config:
        enable: true
        base-url: http://localhost:9009
        report-url: /monitor/data
        health-url: /monitor/down